modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Thutmose/Thut/issues"


[[mods]]
    modId="thutcore"
    version="@VERSION"
    displayName="Thut Core"
    authors="Thutmose"
    description='''
    This is a library of shared functionality for my mods.
    '''
[[mods]]
    modId="thutcrafts"
    version="${file.jarVersion}"
    displayName="Thut Crafts"
    authors="Thutmose"
    description='''
    Tech Demo mod for testing the elevator mod updates.
    '''
    
[[dependencies.thutcore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"